<?php

namespace App\Business\Modules\User;

use App\Domain\Entities\Builders\UserBuilder;
use App\Domain\Entities\Models\User;
use App\Presentation\Http\Requests\User\CreateUserRequest;
use App\Presentation\Http\Requests\User\UpdateUserRequest;

/**
 * Converts "Request Data" into "Domain Objects."
 */
class UserFromRequestFactory
{
    /**
     * @param CreateUserRequest $request
     * @return User
     */
    public function fromCreateRequest(CreateUserRequest $request): User
    {
        return (new UserBuilder())
                ->setId(null) //Id is auto generated by Database
                ->setFirstName($request->getFirstName())
                ->setLastName($request->getLastName())
                ->setEmail($request->getEmail())
                ->setGender($request->getGender())
                ->setPassword($request->getPassword())
                ->setDepartmentId($request->getDepartmentId())
                ->setRoleId($request->getRoleId())
                ->build();
    }

    /**
     * @param int $requested_id
     * @param UpdateUserRequest $request
     * @return User
     */
    public function fromUpdateRequest(int $requested_id, UpdateUserRequest $request): User
    {
        return (new UserBuilder())
                ->setId($requested_id)
                ->setFirstName($request->getFirstName())
                ->setLastName($request->getLastName())
                ->setEmail($request->getEmail())
                ->setGender($request->getGender())
                ->setPassword(null) // Don't update the user's password.
                ->setDepartmentId($request->getDepartmentId())
                ->setRoleId($request->getRoleId())
                ->build();
    }
}